openapi: 3.0.3
info:
  title: ALTA API BE11
  version: 1.0.0
  description: This is a sample server for a pet store.
  termsOfService: https://example.com/terms/
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  url: https://academy.alterra.id
  description: dokumentasi lengkap
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/iffakhry/project1/1.0.0
  - url: http://192.0.1.10
    description: api server
  - url: https://{environment}.api.server.com
    description: server https
    variables:
      environment: 
        default: dev
        enum:
          - "prod"
          - "dev"
tags:
  - name: Pets
paths:
  /pets:
    get:
      tags:
        - Pets
      description: Returns all pets from the system that the user has access to
      responses:
        '200':
          description: A list of pets.
    post:
      description: 'insert pet data'
      parameters: []
      responses:
        '200':
          description: OK
    delete:
      description: 'delete pet data'
      parameters: []
      responses:
        '200':
          description: OK
  /users:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
  /users/{iduser}:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK


